#! /usr/bin/env python

import sys
from argparse import ArgumentParser, RawDescriptionHelpFormatter
import cx_Oracle
from datetime import datetime, timedelta
from time import mktime

COLS = { 'TIMESTAMP': 19,
         'PRIORITY': 10, # 9 + 1 for the comma
         'CPU': 13, # 12 + 1 for the comma
         'STARTED': 7,
         'WALL': 11,
       }

def connect(config):
    return cx_Oracle.connect(open(config).read().strip())

def find(args):
    # Connect to DB
    connection = connect(args.config)
    c = connection.cursor()

    # Query
    sql = "SELECT username FROM users WHERE username LIKE :u"
    c.execute(sql, ['%' + args.user])

    for username, in c:
        print username

def shares(args):
    # Connect to DB
    connection = connect(args.config)
    c = connection.cursor()

    # Query
    select = "SELECT timestamp, priority, started, cpu"
    tables = " FROM users NATURAL JOIN shares"
    where = " WHERE username = :u AND timestamp > :t ORDER BY timestamp"
    sql = select + tables + where
    print sql
    c.execute(sql, [args.group, datetime.now() - timedelta(hours=args.ago)])
    table(c, args.group, '    ')

    # Print user's group hierarchy share values
    if args.recursive:
        hierarchy = args.group.split('/')
        for i in range(1, len(hierarchy) - 1):
            group = '/'.join(hierarchy[:-i])
            c.execute(sql, [group])
            print
            table(c, group, '    ')

def table(cursor, group, indent=None):
    def header(cursor, indent):
        if indent:
            print indent,
        for c, _, _, _, _, _, _ in cursor.description:
            print c + ' ' * (COLS[c] - len(c) + 1),
        print

    # Print group name
    print group + ':\n'

    # Header
    header(cursor, indent)

    # Values
    for row in cursor:
        if indent:
            print indent,
        for col, (c, _, _, _, _, _, _) in zip(row, cursor.description):
            print str(col) + ' ' * (COLS[c] - len(str(col)) + 1),
        print

    # Footer
    header(cursor, indent)

def main():
    # Arguments
    epilogue='''\
You would typically search a given user's charged group first:
% fairshare find fred
SHARE/XX/foo/fred
SHARE/XX/bar/fred

You could then list his share values over time for on of his give groups:
% fairshare shares SHARE/XX/bar/fred
TIMESTAMP            PRIORITY    STARTED  CPU           
1984-06-04 13:20:00  0.333       0        0.0           
1984-06-04 13:30:00  0.333       0        0.0           
1984-06-04 13:40:00  0.333       0        0.0           
1984-06-04 13:50:00  0.047       6        622.0         
1984-06-04 14:00:00  0.312       0        1029.7        
1984-06-04 14:10:00  0.312       0        1029.7        
1984-06-04 14:20:00  0.313       0        1006.2        
1984-06-04 14:30:00  0.313       0        982.3         
1984-06-04 14:40:00  0.313       0        982.3         
1984-06-04 14:50:00  0.314       0        959.0         
1984-06-04 15:00:00  0.314       0        936.3

Here, the user didn't have any job dispatched until 13:50 when 6 started. His
priority consequently decreased and his cumulative CPU usage increased. At
14:00, all of his jobs finished and his cumulative CPU usage, which had reached
a certain amount, subsequently started to decrease and his priority increase
again.'''

    p = ArgumentParser(description='Query fairshare information',
                       epilog=epilogue,
                       formatter_class=RawDescriptionHelpFormatter)
    p.add_argument('-c', '--config', help="config file",
                   default='/etc/fairshare')

    s = p.add_subparsers()

    # Find sub-command
    pfi = s.add_parser('find', help="find user's charged group")
    pfi.add_argument('user', help="user name")
    pfi.set_defaults(func=find)

    # Shares sub-command
    psh = s.add_parser('shares',
                       help="print user's charged group share values over time")
    psh.add_argument('group', help="charged group")
    help = "recursively print all user's parent groups share values too"
    psh.add_argument('-r', '--recursive', action='store_true', help=help)
    psh.add_argument('-a', '--ago', metavar='N', type=int, default=2,
                     help="display share values after N hours ago")
    psh.set_defaults(func=shares)

    args = p.parse_args()
    args.func(args)

if __name__ == '__main__':
    sys.exit(main())
